package server.security;

public enum SecurityEventType {
    MALFORMED_PACKET,
    MUTATION_REPLAY,
    PACKET_RATE_LIMIT,
    AUTOBAN_SIGNAL,
    ADMIN_BRIDGE_REJECTION,
    PLAYER_REPORT_TRIAGE,
    ECONOMY_INVARIANT
}
